import dynamic from 'next/dynamic'
import Head from 'next/head'
import { Byline } from "@/components/byline";
import { Card } from "@/components/card";
import { Code } from "@/components/code";
import { Description } from "@/components/description";
import { Grid } from "@/components/grid";
import { Main } from "@/components/main";

const DynamicHero = dynamic(() => import('@/components/hero').then((x) => x.Hero), {
  loading: () => <p>Loading...</p>,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Description
          left={
            <>
              Get started by editing&nbsp;
              <Code>src/pages/index.tsx</Code>
            </>
          }
          right={<Byline />}
        />

        <DynamicHero />

        <Grid>
          <Card
            title="Docs"
            description="Find in-depth information about Next.js features and&nbsp;API."
            href="https://nextjs.org/docs"
          />

          <Card
            title="Learn"
            description="Learn about Next.js in an interactive course with&nbsp;quizzes!"
            href="https://nextjs.org/learn"
          />

          <Card
            title="Templates"
            description="Discover and deploy boilerplate example Next.js&nbsp;projects."
            href="https://nextjs.org/templates"
          />

          <Card
            title="Deploy"
            description=" Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel."
            href="https://nextjs.org/deploy"
          />
        </Grid>
      </Main>
    </>
  )
}
