import { globalStyle } from "@navita/css";

export const metadata = {
  title: 'Navita Next App',
  description: 'Generated by create next app',
};

globalStyle(':root', {
  background: 'hotpink',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
