[package]
name = "extraction"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_repr = "0.1"
fxhash = "0.2.1"
swc_common = { version = "0.31.12", features = ["concurrent"] }
swc_core = { version = "0.78.0", features = [
    "common",
    "ecma_plugin_transform",
    "ecma_utils"
] }

