name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build (because turbo config is not working correctly?)
        run: pnpm build

      - name: Test
        run: pnpm test
